### ISSUE TITLE
env2 breaks all helper tests and most server tests

### ISSUE THREAD

**Issue by matthewiiv** [pursuit-of-hapiness/wild-wild-wordpress#31]

**Comment by matthewiiv** [comment]
Is this because we need configuration file on our local machines?

**Comment by mcelearr** [comment]
Yes. You need to create a file called config.env on your local machine. I'll send you what to put in there on gitter. You then need to npm install to get env2. Now try running the tests.

**Comment by matthewiiv** [comment]
Great, Fixed
