### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by mcelearr** [pursuit-of-hapiness/wild-wild-wordpress#4]

**Comment by matthewiiv** [comment]
Tables:
CONTENT => id userid title content_body date_created date_updated published
USERS => id username password last_login date_created
TAGS => id postid tag

**Comment by matthewiiv** [comment]
Set up.
View with
psql postgres://qvggfurt:r3jWdQxJdDGRxpuPXrstJb2KlfQ9Gtdn@horton.elephantsql.com:5432/qvggfurt

table names: 
content
users
tags
